baseurl = "https://mlesikov.github.io/hugo-material-docs/"
publishDir = "docs"
languageCode = "en-us"
title = "TelcoNG HUGO Material Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.ico"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light-blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
    name   = "Getting started"
    url    = "getting-started/"
    weight = 10

[[menu.main]]
	name   = "Tutorials"
	url    = "tutorials/"
	weight = 11

[[menu.main]]
    parent = "Tutorials"
    name   = "Contract Signing Tutorial"
    url    = "tutorials/contract_signing/"
    weight = 2

[[menu.main]]
    parent = "Tutorials"
    name   = "Services set up"
    url    = "tutorials/servicesSetUp"
    weight = 3

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
